
services:
  - type: web
    name: ai-notes-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NVIDIA_API_KEY
        sync: false

  - type: web
    name: ai-notes-frontend
    env: static
    buildCommand: npm install && npm run build
    publishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-notes-backend.onrender.com
