// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cajyuoshwjftbizcgoep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhanl1b3Nod2pmdGJpemNnb2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTU4MzksImV4cCI6MjA2Mzk3MTgzOX0.gcbGeVWmmqG_S8lVV6RM189b5RjMvKp2tI4dMb5d3V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);